module.exports = {
  presets: ['babel-preset-expo'],
  overrides: [
    {
      test: filename =>
        typeof filename === 'string' && /\.mtsx?$/.test(filename),
      presets: [
        ['@babel/preset-typescript', {allExtensions: true, isTSX: true}],
      ],
    },
    {
      exclude: filename =>
        typeof filename === 'string' && /node_modules/.test(filename),
      plugins: [
        [
          'module:react-native-dotenv',
          {
            moduleName: '@env',
            path: '.env',
            allowlist: [
              'API_KEY_DEV',
              'API_KEY_TEST',
              'API_KEY_ACC',
              'API_KEY_PROD',
              'BUILD_NUMBER',
              'PIWIK_PRO_ID',
              'PIWIK_PRO_ID_ACCEPT',
              'PIWIK_PRO_URL',
              'PIWIK_PRO_URL_ACCEPT',
              'VERSION',
              'APPLICATION_INSIGHTS_INSTRUMENTATION_KEY_DEV',
              'APPLICATION_INSIGHTS_INSTRUMENTATION_KEY_TEST',
              'APPLICATION_INSIGHTS_INSTRUMENTATION_KEY_ACC',
              'APPLICATION_INSIGHTS_INSTRUMENTATION_KEY_PROD',
              'CHAT_DEVELOPER_NAME_DEV',
              'CHAT_ORGANIZATION_ID_DEV',
              'CHAT_URL_DEV',
              'CHAT_DEVELOPER_NAME_TEST',
              'CHAT_ORGANIZATION_ID_TEST',
              'CHAT_URL_TEST',
              'CHAT_DEVELOPER_NAME_ACC',
              'CHAT_ORGANIZATION_ID_ACC',
              'CHAT_URL_ACC',
              'CHAT_DEVELOPER_NAME_PROD',
              'CHAT_ORGANIZATION_ID_PROD',
              'CHAT_URL_PROD',
            ],
          },
        ],
      ],
    },
  ],
  plugins: [
    // [
    //   'module:react-native-dotenv',
    //   {
    //     moduleName: '@env',
    //     path: '.env',
    //     allowlist: [
    //       'API_KEY_DEV',
    //       'API_KEY_TEST',
    //       'API_KEY_ACC',
    //       'API_KEY_PROD',
    //       'BUILD_NUMBER',
    //       'PIWIK_PRO_ID',
    //       'PIWIK_PRO_ID_ACCEPT',
    //       'PIWIK_PRO_URL',
    //       'PIWIK_PRO_URL_ACCEPT',
    //       'VERSION',
    //       'APPLICATION_INSIGHTS_INSTRUMENTATION_KEY_DEV',
    //       'APPLICATION_INSIGHTS_INSTRUMENTATION_KEY_TEST',
    //       'APPLICATION_INSIGHTS_INSTRUMENTATION_KEY_ACC',
    //       'APPLICATION_INSIGHTS_INSTRUMENTATION_KEY_PROD',
    //       'CHAT_DEVELOPER_NAME_DEV',
    //       'CHAT_ORGANIZATION_ID_DEV',
    //       'CHAT_URL_DEV',
    //       'CHAT_DEVELOPER_NAME_TEST',
    //       'CHAT_ORGANIZATION_ID_TEST',
    //       'CHAT_URL_TEST',
    //       'CHAT_DEVELOPER_NAME_ACC',
    //       'CHAT_ORGANIZATION_ID_ACC',
    //       'CHAT_URL_ACC',
    //       'CHAT_DEVELOPER_NAME_PROD',
    //       'CHAT_ORGANIZATION_ID_PROD',
    //       'CHAT_URL_PROD',
    //     ],
    //   },
    // ],
    ['@babel/plugin-transform-flow-strip-types', {allowDeclareFields: true}],
    'react-native-worklets/plugin',
  ],
}
