export enum RedirectEndpointName {
  getRedirectUrls = 'getRedirectUrls',
}

export enum RedirectKey {
  acknowledgeChild = 'acknowledgeChild',
  birth = 'birth',
  chatPrivacy = 'chatPrivacy',
  cityPassChildBudget = 'cityPassChildBudget',
  cityPassLowIncomeSupport = 'cityPassLowIncomeSupport',
  cityPassRequest = 'cityPassRequest',
  cityPassUsage = 'cityPassUsage',
  citypass = 'citypass',
  contactForm = 'contactForm',
  contactNewsletterSignup = 'contactNewsletterSignup',
  documents = 'documents',
  elections = 'elections',
  feedbackForm = 'feedbackForm',
  immigration = 'immigration',
  income_help = 'income_help',
  lifelessBirth = 'lifelessBirth',
  makeAppointMentWeesp = 'makeAppointMentWeesp',
  marriage = 'marriage',
  marriagePermission = 'marriagePermission',
  my_parking = 'my_parking',
  my_reported_problems = 'my_reported_problems',
  naturalisation = 'naturalisation',
  parking = 'parking',
  parking_request_license_plate_ga_bewoners = 'parking_request_license_plate_ga_bewoners',
  parking_request_license_plate_ga_bezoekers = 'parking_request_license_plate_ga_bezoekers',
  parking_request_license_plate_mantelzorgers = 'parking_request_license_plate_mantelzorgers',
  passing = 'passing',
  passingForFuneralDirectors = 'passingForFuneralDirectors',
  relocation = 'relocation',
  reported_problems_map = 'reported_problems_map',
  rivm_report = 'rivm_report',
  sailingAndMooring = 'sailingAndMooring',
  waste = 'waste',
  waste_extra_info = 'waste_extra_info',
}
