name: PR labels
on:
  pull_request:
    branches: [main]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]

permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: write

jobs:
  pr-labels:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/install-node

      - name: Install dependencies
        run: npm run ci

      - name: Annotate PR with labels
        run: node nodescripts/pr-label.mts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
